apiVersion: v1
kind: Service
metadata:
  name: simple-backend-svc
  namespace: app1-ns
spec:
  type: ClusterIP
  selector:
    app: simple-backend
  ports:
    - name: http
      port: 80
      targetPort: 5000 

  